### ISSUE TITLE
instal_lib.sh yields error on Installation of SuAVE 2.24.07

### ISSUE THREAD

**Issue by StochasticCactus** [SuAVE-Software/source_v2.0#4]
Hi, I'm trying to install the new version of SuAVE, and got this error:

> mkdir: build: File exists
> CMake Error: The current CMakeCache.txt directory /Users/tarcillo/Desktop/suave_src_mod/library/libxdrfile-master/build/CMakeCache.txt is different than the directory /home/dsantos/Dropbox/SuAVE/src_mod/library/libxdrfile-master/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
> CMake Error: The source "/Users/tarcillo/Desktop/suave_src_mod/library/libxdrfile-master/CMakeLists.txt" does not match the source "/home/dsantos/Dropbox/SuAVE/src_mod/library/libxdrfile-master/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
> make: /usr/local/bin/cmake: No such file or directory
> make: *** [cmake_check_build_system] Error 1
> mkdir: build: File exists
> CMake Error: The current CMakeCache.txt directory /Users/tarcillo/Desktop/suave_src_mod/library/libgmxfort-master/build/CMakeCache.txt is different than the directory /home/dsantos/Dropbox/SuAVE/src_mod/library/libgmxfort-master/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
> CMake Error: The source "/Users/tarcillo/Desktop/suave_src_mod/library/libgmxfort-master/CMakeLists.txt" does not match the source "/home/dsantos/Dropbox/SuAVE/src_mod/library/libgmxfort-master/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
> make: /usr/local/bin/cmake: No such file or directory
> make: *** [cmake_check_build_system] Error 1

It seems that the CMake cache files were configured to your personal directories, I tried deleting the CMake cache files but got this error:

> CMake Error at cmake/xdrfile.cmake:21 (find_package):
>   By not providing "Findxdrfile.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "xdrfile", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "xdrfile" with any
>   of the following names:
> 
>     xdrfileConfig.cmake
>     xdrfile-config.cmake
> 
>   Add the installation prefix of "xdrfile" to CMAKE_PREFIX_PATH or set
>   "xdrfile_DIR" to a directory containing one of the above files.  If
>   "xdrfile" provides a separate development package or SDK, be sure it has
>   been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:38 (include)

It seems that there is an error in the CMake files. 

I'm looking forward to use SuAVE with this new xtc file compatibility feature.

Thanks

**Comment by SuAVE-Software** [comment]
Thank you for the message.

We would like to suggest that you try using this file instead of the previous install_lib.sh.
The file is already updated on the main page.

----------------------------------------------------------------------------------------------------
#!/bin/bash                                                                                                                                                                                                  
                                                                                                                                                         
cd library/libxdrfile-master/
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
make
sudo make install
cd ../../..                                                                                                                                                        
                                                                                                                                                         
cd library/libgmxfort-master/
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
make
sudo make install
cd ../../..

-----------------------------------------------------------------------------------------------------------
